version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - observability

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - observability

  app:
    build: ./app
    entrypoint: ./entrypoint.sh
    container_name: app
    volumes:
    - .:/app
    ports:
    - 5000:5000
    networks:
      - observability

networks:
  observability:
    external: true